name: CI

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9  # Remplacez "3.x" par la version de Python que vous utilisez


    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV


    - name: Print sys.path
      run: python -c "import sys; print(sys.path)"

    - name: Install mongodb
      uses: supercharge/mongodb-github-action@1.10.0

    - name: Create logs folder
      run: mkdir -p $GITHUB_WORKSPACE/logs

    - name: Change to the repository root
      run: cd $GITHUB_WORKSPACE

    - name: Run tests
      run: |
        pytest ./tests/conftest.py

    - name: Run linter (exemple avec flake8)
      run: |
        pip install flake8
        flake8 .

#   publish: 
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read
#     needs : testing
#     if : success()

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4.1.1
    
#     - name : set up acorn
#       uses: acorn-io/actions-setup@v1

#     - name: login
#       uses: acorn-io/actions-login@v1
#       with: 
#         registry : docker.io
#         username : ${{ secrets.DOCKERHUB_USERNAME }}
#         password : ${{ secrets.DOCKERHUB_TOKEN }}
      
#     - name: build  
#       run: |
#         acorn build -t index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/scaper:main .
#         acorn push index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/scaper:main

#     - name: Dockerhub login
#       uses: docker/login-action@v3.0.0
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#     # - name: Log in to the Container registry
#     #   uses: docker/login-action@v3.0.0
#     #   with:
#     #     registry: ghcr.io
#     #     username: ${{ github.actor }}
#     #     password: ${{ secrets.GITHUB_TOKEN }}
          
#     - name: metadata extraction
#       id: meta
#       uses: docker/metadata-action@v5.5.0
#       with:
#         images: Insiares/Scraper
      
#     - name: Build and push
#       uses: docker/build-push-action@v5.1.0
#       with:
#         context: .
#         file : ./Dockerfile
#         push: true
#         tags: ${{ steps.meta.outputs.tags }}
#         labels: ${{ steps.meta.outputs.labels }}